version: "3"
services:
  db:
    image: postgres
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: model-test
      POSTGRES_PASSWORD: password
    # volumes:
    #   - "db-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  testdata:
    build: ./containers/build_data/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  textblob:
    build: ./containers/textblob_model/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  vader:
    build: ./containers/vader_model/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  random:
    build: ./containers/random_model/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  calcmetrics:
    build: ./containers/calc_metrics/
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
  dash:
    build: ./containers/make_dash/
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
    environment:
      PGHOST: db
      PGUSER: root
      PGDATABASE: model-test
      PGPASSWORD: password
    ports:
      - 8080:8080

# volumes:
#   db-data:
#     driver: local
